import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties, type FormEvent, type KeyboardEvent as ReactKeyboardEvent } from 'react';
import { Background, Controls, Handle, Position, ReactFlow, type Node, type ReactFlowInstance } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { CLIENT_ROOT_ENTITY_KINDS, addEntity, addTouchpointContainer, createEmptyMapDocument, duplicateEntity, isClientRootEntityKind, isContextualClientEntityKind, movePlacement, updateEntity, updateRepulsorTargets, type ContextualClientEntityKind, type Entity, type MapDocument, type ProvisionalEntityKind, type Relationship } from '@vee/domain';
import { deriveMapEdges, deriveMapNodes, KIND_LABELS, type MapNodeData } from '../map-adapter';
import { contextMenuPoint, linkedOfferIds, overlayPoint, parentTouchpointOptions, siblingDraft, siblingPlacement, type Point } from '../map-interaction';
import { Link } from '../router';

const VIEW_ID = 'spike-view';
const INITIAL_DOCUMENT = createEmptyMapDocument({ mapId: 'spike-map', title: 'Untitled validation map', viewId: VIEW_ID, viewTitle: 'Working view' });
type Side = 'business' | 'client';
type Draft = { title: string; side: Side; kind: ProvisionalEntityKind; linkedProductId: string; linkedOfferIds: string[]; locatedInId: string; locatedInQuery: string; parentTouchpointId: string; parentEntityId: string; resistedTargetIds: string[]; url: string };
type Menu = { type: 'canvas'; client: Point; overlay: Point; flow: Point; positioned: boolean } | { type: 'node'; client: Point; overlay: Point; entityId: string; positioned: boolean };
type Quick = { draft: Draft; overlay: Point; flow: Point };
type ChildChooser = { parentEntityId: string; overlay: Point; flow: Point };
const draft = (kind: ProvisionalEntityKind = 'product'): Draft => ({ title: '', side: isClientRootEntityKind(kind) || isContextualClientEntityKind(kind) || kind === 'repulsor' ? 'client' : 'business', kind, linkedProductId: '', linkedOfferIds: [], locatedInId: '', locatedInQuery: '', parentTouchpointId: '', parentEntityId: '', resistedTargetIds: [], url: '' });
const isControl = (target: EventTarget | null) => target instanceof HTMLElement && Boolean(target.closest('input, textarea, select, button, [role="combobox"], [contenteditable], form, .contextual-editor'));
const safeUrl = (url?: string) => url && !/^\s*(javascript|data):/i.test(url) ? url : undefined;

function ContainerCombobox({ value, query, document, onChange }: { value: string; query: string; document: MapDocument; onChange: (id: string, query: string, create?: boolean) => void }) {
  const [open, setOpen] = useState(false); const normalized = query.trim().toLocaleLowerCase();
  const matches = document.touchpointContainers.filter(c => c.title.toLocaleLowerCase().includes(normalized));
  const exact = document.touchpointContainers.find(c => c.title.trim().toLocaleLowerCase() === normalized);
  return <div className="combobox"><label>Located in<input role="combobox" aria-expanded={open} aria-controls="container-options" required value={query} onFocus={() => setOpen(true)} onChange={e => { setOpen(true); onChange('', e.target.value); }} onKeyDown={e => { if (e.key === 'Escape') setOpen(false); }} /></label>
    {open && <div id="container-options" role="listbox">{matches.map(c => <button type="button" role="option" aria-selected={value === c.id} key={c.id} onClick={() => { onChange(c.id, c.title); setOpen(false); }}>{c.title}</button>)}
      {normalized && !exact && <button type="button" onClick={() => { onChange('', query.trim(), true); setOpen(false); }}>Create &quot;{query.trim()}&quot;</button>}</div>}</div>;
}
export function MapNode({ data }: { data: MapNodeData }) { const url = safeUrl(data.url); const style = { '--node-title-size': `${data.layout.titleFontSize}px`, '--node-kind-size': `${data.layout.kindFontSize}px`, '--node-content-width': `${data.layout.contentWidth}px` } as CSSProperties; return <div className={`node-content${data.layout.compactTitle ? ' compact-title' : ''}`} style={style}><Handle type="target" position={Position.Left} isConnectable={false} /><strong>{data.title}</strong><span>{data.kindLabel}</span>{url && <a className="node-link nodrag nopan" href={url} target="_blank" rel="noreferrer" aria-label={`Open ${data.title}`} onPointerDown={e => e.stopPropagation()} onClick={e => e.stopPropagation()}>↗</a>}<Handle type="source" position={Position.Right} isConnectable={false} /></div>; }

export function MapSpike() {
  const panelRef = useRef<HTMLElement>(null); const menuRef = useRef<HTMLDivElement>(null); const flowRef = useRef<ReactFlowInstance<Node<MapNodeData>> | null>(null);
  const [document, setDocument] = useState<MapDocument>(INITIAL_DOCUMENT); const documentRef = useRef(document); documentRef.current = document;
  const [selectedId, setSelectedId] = useState<string | null>(null); const selectedRef = useRef(selectedId); selectedRef.current = selectedId;
  const [mode, setMode] = useState<'idle' | 'create'>('idle'); const [createDraft, setCreateDraft] = useState<Draft>(draft());
  const [editDraft, setEditDraft] = useState<Draft | null>(null); const [menu, setMenu] = useState<Menu | null>(null); const [quick, setQuick] = useState<Quick | null>(null);
  const [childChooser, setChildChooser] = useState<ChildChooser | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null); const copiedRef = useRef(copiedId); copiedRef.current = copiedId; const [message, setMessage] = useState('');
  const nodes = deriveMapNodes(document, VIEW_ID, selectedId).map(node => ({ ...node, type: 'mapNode' })); const edges = deriveMapEdges(document); const selected = document.entities.find(e => e.id === selectedId);

  useLayoutEffect(() => {
    const panel = panelRef.current; const element = menuRef.current;
    if (!menu || !panel || !element || menu.positioned) return;
    const bounds = element.getBoundingClientRect();
    const overlay = contextMenuPoint(menu.client, panel.getBoundingClientRect(), { width: bounds.width, height: bounds.height });
    setMenu({ ...menu, overlay, positioned: true });
  }, [menu]);

  function draftFor(entity: Entity, source = document): Draft { const result = draft(entity.kind); result.title = entity.title; if (entity.kind === 'offer') result.linkedProductId = source.relationships.find((r): r is Extract<Relationship, { kind: 'product_packaged_as_offer' }> => r.kind === 'product_packaged_as_offer' && r.offerId === entity.id)?.productId ?? ''; if (entity.kind === 'touchpoint') { result.linkedOfferIds = linkedOfferIds(source, entity.id); result.parentTouchpointId = source.relationships.find((r): r is Extract<Relationship, { kind: 'touchpoint_contains_touchpoint' }> => r.kind === 'touchpoint_contains_touchpoint' && r.childTouchpointId === entity.id)?.parentTouchpointId ?? ''; result.locatedInId = entity.locatedInId; result.locatedInQuery = source.touchpointContainers.find(c => c.id === entity.locatedInId)?.title ?? ''; result.url = entity.url ?? ''; } if (entity.kind === 'related_job') result.parentEntityId = source.relationships.find((r): r is Extract<Relationship, { kind: 'core_functional_job_has_related_job' }> => r.kind === 'core_functional_job_has_related_job' && r.relatedJobId === entity.id)?.coreFunctionalJobId ?? ''; if (entity.kind === 'desired_outcome') result.parentEntityId = source.relationships.find((r): r is Extract<Relationship, { kind: 'job_has_desired_outcome' }> => r.kind === 'job_has_desired_outcome' && r.desiredOutcomeId === entity.id)?.jobId ?? ''; if (entity.kind === 'repulsor') result.resistedTargetIds = source.relationships.filter((r): r is Extract<Relationship, { kind: 'repulsor_resists' }> => r.kind === 'repulsor_resists' && r.repulsorId === entity.id).map(r => r.targetEntityId); return result; }
  function select(id: string | null) { setSelectedId(id); setMode('idle'); setQuick(null); setChildChooser(null); setMenu(null); setMessage(''); const entity = document.entities.find(e => e.id === id); setEditDraft(entity ? draftFor(entity) : null); }
  function childDraft(entity: Entity, contextualKind?: ContextualClientEntityKind | 'repulsor'): Draft | null { if (contextualKind === 'repulsor') { const d = draft('repulsor'); d.resistedTargetIds = [entity.id]; return d; } if (contextualKind) { const d = draft(contextualKind); d.parentEntityId = entity.id; return d; } if (entity.kind === 'emotional_job' || entity.kind === 'social_job' || entity.kind === 'financial_desired_outcome') { const d = draft('repulsor'); d.resistedTargetIds = [entity.id]; return d; } if (isClientRootEntityKind(entity.kind) || isContextualClientEntityKind(entity.kind) || entity.kind === 'repulsor') return null; if (entity.kind === 'product') { const d = draft('offer'); d.linkedProductId = entity.id; return d; } if (entity.kind === 'offer') { const d = draft('touchpoint'); d.linkedOfferIds = [entity.id]; return d; } if (entity.kind !== 'touchpoint') return null; const d = draft('touchpoint'); d.parentTouchpointId = entity.id; d.linkedOfferIds = linkedOfferIds(documentRef.current, entity.id); d.locatedInId = entity.locatedInId; d.locatedInQuery = documentRef.current.touchpointContainers.find(c => c.id === entity.locatedInId)?.title ?? ''; return d; }
  function localForFlow(point: Point): Point { const panel = panelRef.current; const instance = flowRef.current; if (!panel || !instance) return point; return overlayPoint(instance.flowToScreenPosition(point), panel.getBoundingClientRect(), { width: 304, height: 360 }); }
  function startChild(id: string, contextualKind?: ContextualClientEntityKind | 'repulsor') { const source = documentRef.current; const entity = source.entities.find(e => e.id === id); if (!entity) return; const placement = source.placements.find(p => p.entityId === id && p.viewId === VIEW_ID)!; const siblings = source.relationships.filter(r => (r.kind === 'product_packaged_as_offer' && r.productId === id) || (r.kind === 'offer_presented_at_touchpoint' && r.offerId === id) || (r.kind === 'touchpoint_contains_touchpoint' && r.parentTouchpointId === id) || (r.kind === 'core_functional_job_has_related_job' && r.coreFunctionalJobId === id) || (r.kind === 'job_has_desired_outcome' && r.jobId === id) || (r.kind === 'repulsor_resists' && r.targetEntityId === id)).length; const flow = { x: placement.x + 190, y: placement.y + siblings * 125 }; const overlay = localForFlow(flow); if ((entity.kind === 'core_functional_job' || entity.kind === 'consumption_chain_job') && !contextualKind) { setChildChooser({ parentEntityId: id, flow, overlay }); setMenu(null); setMessage(''); return; } const d = childDraft(entity, contextualKind); if (!d) return; setQuick({ draft: d, flow, overlay }); setChildChooser(null); setMenu(null); setMessage(''); }
  function startSibling(id: string) { const source = documentRef.current; const context = siblingDraft(source, id); const flow = siblingPlacement(source, id, VIEW_ID); if (!context || !flow) return; setQuick({ draft: { ...draft(context.kind), ...context }, flow, overlay: localForFlow(flow) }); setMenu(null); setMessage(''); }
  function ensureContainer(current: MapDocument, d: Draft): [MapDocument, string] { if (d.locatedInId) return [current, d.locatedInId]; const exact = current.touchpointContainers.find(c => c.title.trim().toLocaleLowerCase() === d.locatedInQuery.trim().toLocaleLowerCase()); if (exact) return [current, exact.id]; const id = crypto.randomUUID(); return [addTouchpointContainer(current, { id, title: d.locatedInQuery }), id]; }
  function createFrom(d: Draft, x: number, y: number): [MapDocument, string] { let current = document; let locatedInId = d.locatedInId; if (d.kind === 'touchpoint') [current, locatedInId] = ensureContainer(current, d); const entityId = crypto.randomUUID(); const common = { entityId, title: d.title, viewId: VIEW_ID, x, y }; const next = d.kind === 'offer' ? addEntity(current, { ...common, kind: 'offer', linkedProductId: d.linkedProductId, relationshipId: crypto.randomUUID() }) : d.kind === 'touchpoint' ? addEntity(current, { ...common, kind: 'touchpoint', locatedInId, url: d.url, linkedOfferIds: d.linkedOfferIds, relationshipIds: d.linkedOfferIds.map(() => crypto.randomUUID()), ...(d.parentTouchpointId ? { parentTouchpointId: d.parentTouchpointId, parentRelationshipId: crypto.randomUUID() } : {}) }) : isContextualClientEntityKind(d.kind) ? addEntity(current, { ...common, kind: d.kind, parentEntityId: d.parentEntityId, relationshipId: crypto.randomUUID() }) : d.kind === 'repulsor' ? addEntity(current, { ...common, kind: 'repulsor', resistedTargetIds: d.resistedTargetIds, relationshipIds: d.resistedTargetIds.map(() => crypto.randomUUID()) }) : addEntity(current, { ...common, kind: d.kind }); return [next, entityId]; }
  function commit(d: Draft, x: number, y: number) { try { const [next, id] = createFrom(d, x, y); setDocument(next); setSelectedId(id); const created = next.entities.find(e => e.id === id)!; setEditDraft(draftFor(created, next)); setQuick(null); setMode('idle'); setMessage('Element created.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Element could not be created.'); } }
  function duplicate(id: string) { const source = documentRef.current; const placement = source.placements.find(p => p.entityId === id && p.viewId === VIEW_ID); if (!placement || !source.entities.some(e => e.id === id)) return; const entityId = crypto.randomUUID(); try { const next = duplicateEntity(source, { sourceEntityId: id, entityId, viewId: VIEW_ID, x: placement.x + 40, y: placement.y + 40, relationshipIds: Array.from({ length: source.relationships.length + 2 }, () => crypto.randomUUID()) }); const created = next.entities.find(e => e.id === entityId)!; setDocument(next); setSelectedId(entityId); setEditDraft(draftFor(created, next)); setMenu(null); setMessage('Element duplicated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Element could not be duplicated.'); } }

  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMenu(null); setQuick(null); setChildChooser(null); return; } if (isControl(event.target)) return; const modifier = event.ctrlKey || event.metaKey; if (modifier && event.key.toLowerCase() === 'c' && selectedRef.current) { event.preventDefault(); setCopiedId(selectedRef.current); } else if (modifier && event.key.toLowerCase() === 'v' && copiedRef.current) { event.preventDefault(); duplicate(copiedRef.current); } else if (event.key === 'Tab' && selectedRef.current) { const entity = documentRef.current.entities.find(e => e.id === selectedRef.current); if (entity && (isClientRootEntityKind(entity.kind) || !isClientRootEntityKind(entity.kind) && !isContextualClientEntityKind(entity.kind) && entity.kind !== 'repulsor')) { event.preventDefault(); startChild(entity.id); } } else if (!modifier && event.key === 'Enter' && selectedRef.current) { event.preventDefault(); startSibling(selectedRef.current); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); });
  function containerChange(setter: (d: Draft) => void, d: Draft, id: string, query: string, create?: boolean) { if (create) { const existing = document.touchpointContainers.find(c => c.title.trim().toLocaleLowerCase() === query.toLocaleLowerCase()); if (existing) setter({ ...d, locatedInId: existing.id, locatedInQuery: existing.title }); else { const id = crypto.randomUUID(); setDocument(current => addTouchpointContainer(current, { id, title: query })); setter({ ...d, locatedInId: id, locatedInQuery: query }); } } else setter({ ...d, locatedInId: id, locatedInQuery: query }); }
  function touchFields(d: Draft, setter: (d: Draft) => void, inspector = false) { if (d.kind !== 'touchpoint') return null; const touchpoints = parentTouchpointOptions(document, inspector ? selectedId ?? undefined : undefined); return <><ContainerCombobox value={d.locatedInId} query={d.locatedInQuery} document={document} onChange={(id, q, create) => containerChange(setter, d, id, q, create)} /><label>URL <span>(optional)</span><input value={d.url} onChange={e => setter({ ...d, url: e.target.value })} /></label>{inspector && <><fieldset><legend>Linked Offers</legend>{document.entities.filter(e => e.kind === 'offer').map(o => <label className="checkbox" key={o.id}><input type="checkbox" checked={d.linkedOfferIds.includes(o.id)} onChange={e => setter({ ...d, linkedOfferIds: e.target.checked ? [...d.linkedOfferIds, o.id] : d.linkedOfferIds.filter(id => id !== o.id) })} />{o.title}</label>)}</fieldset><label>Parent Touchpoint<select value={d.parentTouchpointId} onChange={e => setter({ ...d, parentTouchpointId: e.target.value })}><option value="">No parent</option>{touchpoints.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label></>}</>; }
  function repulsorTargetsField(d: Draft, setter: (d: Draft) => void) { if (d.kind !== 'repulsor') return null; return <fieldset><legend>Resists</legend>{document.entities.filter(entity => isClientRootEntityKind(entity.kind)).map(entity => <label className="checkbox" key={entity.id}><input type="checkbox" checked={d.resistedTargetIds.includes(entity.id)} onChange={event => setter({ ...d, resistedTargetIds: event.target.checked ? [...d.resistedTargetIds, entity.id] : d.resistedTargetIds.filter(id => id !== entity.id) })} />{entity.title} · {KIND_LABELS[entity.kind]}</label>)}</fieldset>; }
  function semanticParentField(d: Draft, setter: (d: Draft) => void) { if (!isContextualClientEntityKind(d.kind)) return null; const validKinds = d.kind === 'related_job' ? ['core_functional_job'] : ['core_functional_job', 'consumption_chain_job']; return <label>Semantic parent<select required value={d.parentEntityId} onChange={e => setter({ ...d, parentEntityId: e.target.value })}>{document.entities.filter(entity => validKinds.includes(entity.kind)).map(entity => <option key={entity.id} value={entity.id}>{entity.title}</option>)}</select></label>; }
  function quickForm(q: Quick) { return <form className="contextual-editor" style={{ left: q.overlay.x, top: q.overlay.y }} onSubmit={e => { e.preventDefault(); commit(q.draft, q.flow.x, q.flow.y); }} onKeyDown={(e: ReactKeyboardEvent) => { if (e.key === 'Escape') { e.stopPropagation(); setQuick(null); } }}><h3>Add {KIND_LABELS[q.draft.kind]}</h3><label>Title<input autoFocus required value={q.draft.title} onChange={e => setQuick({ ...q, draft: { ...q.draft, title: e.target.value } })} /></label>{touchFields(q.draft, d => setQuick({ ...q, draft: d }))}{q.draft.kind === 'repulsor' && <p>Resists: {q.draft.resistedTargetIds.map(id => document.entities.find(entity => entity.id === id)?.title).join(', ')}</p>}<div className="actions"><button className="primary">Create</button><button type="button" onClick={() => setQuick(null)}>Cancel</button></div>{message && <p className="error-message" role="alert">{message}</p>}</form>; }

  return <main className="map-page"><header className="map-header"><div><Link to="/">VEE Software</Link><h1>Map-first authoring spike</h1><p>In-memory authored 2D map. Select a node and press Tab to add its canonical child.</p></div><button className="primary" onClick={() => { setMode('create'); setCreateDraft(draft()); }}>Add element</button></header><div className="editor-layout">
    <section ref={panelRef} className="canvas-panel" aria-label="In-memory VEE map editor">
      {!document.entities.length && <div className="empty-state"><h2>Start an empty map</h2><p>Right-click the canvas or add an element.</p></div>}
      <ReactFlow<Node<MapNodeData>> aria-label="Map canvas" nodes={nodes} edges={edges} nodeTypes={{ mapNode: MapNode }} fitView nodesConnectable={false} edgesFocusable={false} deleteKeyCode={null} multiSelectionKeyCode={null} onInit={instance => { flowRef.current = instance; }} onPaneClick={() => { select(null); setMenu(null); }} onPaneContextMenu={e => { e.preventDefault(); const client = { x: e.clientX, y: e.clientY }; const panel = panelRef.current; const instance = flowRef.current; if (!panel || !instance) return; setMenu({ type: 'canvas', client, overlay: overlayPoint(client, panel.getBoundingClientRect()), flow: instance.screenToFlowPosition(client), positioned: false }); }} onNodeClick={(_, node) => select(node.id)} onNodeContextMenu={(e, node) => { e.preventDefault(); const client = { x: e.clientX, y: e.clientY }; const panel = panelRef.current; if (!panel) return; setMenu({ type: 'node', client, overlay: overlayPoint(client, panel.getBoundingClientRect()), entityId: node.id, positioned: false }); }} onNodeDragStop={(_, node) => setDocument(current => movePlacement(current, { entityId: node.id, viewId: VIEW_ID, x: node.position.x, y: node.position.y }))}><Background color="rgba(255,255,255,.12)" /><Controls showInteractive={false} /></ReactFlow>
      {menu && <div ref={menuRef} className="context-menu" role="menu" style={{ left: menu.overlay.x, top: menu.overlay.y, visibility: menu.positioned ? 'visible' : 'hidden' }}>{menu.type === 'canvas' ? <><span>Business side</span><button role="menuitem" onClick={() => { const panel = panelRef.current!; setQuick({ draft: draft('product'), overlay: overlayPoint(menu.client, panel.getBoundingClientRect(), { width: 304, height: 360 }), flow: menu.flow }); setMenu(null); }}>Product</button><span>Client side</span>{CLIENT_ROOT_ENTITY_KINDS.map(kind => <button key={kind} role="menuitem" onClick={() => { const panel = panelRef.current!; setQuick({ draft: draft(kind), overlay: overlayPoint(menu.client, panel.getBoundingClientRect(), { width: 304, height: 360 }), flow: menu.flow }); setMenu(null); }}>{KIND_LABELS[kind]}</button>)}</> : (() => { const entity = document.entities.find(e => e.id === menu.entityId); if (!entity) return null; const url = entity.kind === 'touchpoint' ? safeUrl(entity.url) : undefined; const canAddChild = isClientRootEntityKind(entity.kind) || !isClientRootEntityKind(entity.kind) && !isContextualClientEntityKind(entity.kind) && entity.kind !== 'repulsor'; return <>{canAddChild && <button role="menuitem" onClick={() => startChild(entity.id)}>Add child</button>}<button role="menuitem" onClick={() => startSibling(entity.id)}>Add sibling</button><button role="menuitem" onClick={() => duplicate(entity.id)}>Duplicate</button>{url && <a role="menuitem" href={url} target="_blank" rel="noreferrer">Open link</a>}</>; })()}</div>}{childChooser && <div className="contextual-editor" role="dialog" aria-label="Choose child type" style={{ left: childChooser.overlay.x, top: childChooser.overlay.y }}><h3>Add child</h3>{(document.entities.find(entity => entity.id === childChooser.parentEntityId)?.kind === 'core_functional_job' ? ['related_job', 'desired_outcome', 'repulsor'] as const : ['desired_outcome', 'repulsor'] as const).map(kind => <button key={kind} type="button" onClick={() => startChild(childChooser.parentEntityId, kind)}>{KIND_LABELS[kind]}</button>)}<button type="button" onClick={() => setChildChooser(null)}>Cancel</button></div>}{quick && quickForm(quick)}
    </section><aside className="inspector" aria-labelledby="inspector-title"><h2 id="inspector-title">Entity inspector</h2>{message && !quick && <p className="status-message" role="status">{message}</p>}
      {mode === 'create' ? <form onSubmit={e => { e.preventDefault(); commit(createDraft, 80 + document.entities.length * 30, 80 + document.entities.length * 30); }}><h3>Add an element</h3><fieldset><legend>Choose a side</legend><div className="choice-row"><button type="button" onClick={() => setCreateDraft(draft('product'))}>Business side</button><button type="button" onClick={() => setCreateDraft(draft('core_functional_job'))}>Client side</button></div></fieldset>{createDraft.side === 'business' ? <label>Business element type<select value={createDraft.kind} onChange={e => setCreateDraft(draft(e.target.value as ProvisionalEntityKind))}><option value="product">Product</option><option value="offer">Offer</option><option value="touchpoint">Touchpoint</option></select></label> : <label>Client element type<select value={createDraft.kind} onChange={e => setCreateDraft(draft(e.target.value as ProvisionalEntityKind))}>{CLIENT_ROOT_ENTITY_KINDS.map(kind => <option key={kind} value={kind}>{KIND_LABELS[kind]}</option>)}</select></label>}<label>Title<input required value={createDraft.title} onChange={e => setCreateDraft({ ...createDraft, title: e.target.value })} /></label>{createDraft.kind === 'offer' && <label>Linked Product<select required value={createDraft.linkedProductId} onChange={e => setCreateDraft({ ...createDraft, linkedProductId: e.target.value })}><option value="">Choose a Product</option>{document.entities.filter(e => e.kind === 'product').map(e => <option key={e.id} value={e.id}>{e.title}</option>)}</select></label>}{createDraft.kind === 'touchpoint' && <><fieldset><legend>Linked Offers</legend>{document.entities.filter(e => e.kind === 'offer').map(o => <label className="checkbox" key={o.id}><input type="checkbox" onChange={e => setCreateDraft({ ...createDraft, linkedOfferIds: e.target.checked ? [...createDraft.linkedOfferIds, o.id] : createDraft.linkedOfferIds.filter(id => id !== o.id) })} />{o.title}</label>)}</fieldset>{touchFields(createDraft, setCreateDraft)}</>}<div className="actions"><button className="primary">Create element</button><button type="button" onClick={() => setMode('idle')}>Cancel</button></div></form>
      : selected && editDraft ? <form onSubmit={(e: FormEvent) => { e.preventDefault(); try { const old = document.relationships.filter(r => r.kind === 'offer_presented_at_touchpoint' && r.touchpointId === selected.id); const parent = document.relationships.find(r => r.kind === 'touchpoint_contains_touchpoint' && r.childTouchpointId === selected.id); let next = updateEntity(document, { entityId: selected.id, title: editDraft.title, linkedProductId: editDraft.linkedProductId, locatedInId: editDraft.locatedInId, url: editDraft.url, linkedOfferIds: editDraft.linkedOfferIds, relationshipIds: editDraft.linkedOfferIds.map((_, i) => old[i]?.id ?? crypto.randomUUID()), parentEntityId: editDraft.parentEntityId, ...(editDraft.parentTouchpointId ? { parentTouchpointId: editDraft.parentTouchpointId, parentRelationshipId: parent?.id ?? crypto.randomUUID() } : {}) }); if (selected.kind === 'repulsor') { const existingTargetIds = document.relationships.flatMap(r => r.kind === 'repulsor_resists' && r.repulsorId === selected.id ? [r.targetEntityId] : []); const addedCount = editDraft.resistedTargetIds.filter(id => !existingTargetIds.includes(id)).length; next = updateRepulsorTargets(next, { repulsorId: selected.id, targetEntityIds: editDraft.resistedTargetIds, newRelationshipIds: Array.from({ length: addedCount }, () => crypto.randomUUID()) }); } setDocument(next); setMessage('Changes applied.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Changes could not be applied.'); } }}><h3>{selected.title}</h3><p>{editDraft.side === 'business' ? 'Business side' : 'Client side'} · {KIND_LABELS[selected.kind]} <span className="immutable-note">(type and side cannot be changed)</span></p><label>Title<input required value={editDraft.title} onChange={e => setEditDraft({ ...editDraft, title: e.target.value })} /></label>{selected.kind === 'offer' && <label>Linked Product<select value={editDraft.linkedProductId} onChange={e => setEditDraft({ ...editDraft, linkedProductId: e.target.value })}>{document.entities.filter(e => e.kind === 'product').map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}{semanticParentField(editDraft, setEditDraft)}{repulsorTargetsField(editDraft, setEditDraft)}{touchFields(editDraft, setEditDraft, true)}{selected.kind === 'touchpoint' && safeUrl(editDraft.url) && <a href={safeUrl(editDraft.url)} target="_blank" rel="noreferrer">Open {editDraft.title}</a>}<button className="primary">Apply changes</button></form> : <p>{document.entities.length ? 'Select an element on the map to inspect and edit it.' : 'Right-click the map to begin authoring.'}</p>}
    </aside></div></main>;
}
